all: p1a p1b p1c
p1a: program01.c
	gcc -o program01 program01.c
p1b: example01.c
	gcc -o example01 example01.c
p1c: example02.c
	gcc -o example02 example02.c
clean:
	rm -f program01 example01 example02
